### ISSUE TITLE
Units mmol/l - raw data xDrip

### ISSUE THREAD

**Issue by infossk** [cmtjk/LinkUpConnect#1]
First of all, I want to thank you for your work on this project. 
But I want to point out one problem in version 1.3.  Changing the glucose units to mmol/l misinterpretation of values ​​in xDrip.  Therefore, it would be correct to continue sending blood glucose to xDrip in mg/Dl as raw values.  In notifications, glycemia can be displayed in any (preferably user-set) unit. Thank you.

**Comment by cmtjk** [comment]
Thanks for reporting. To be honest, I didn't seriously test it since I use mg/dl. I had a quick look at the xDrip code and somehow thought a mmol/l<->mg/dl converter kicks in since testing it with fixed unrealistic values didn't reveal something suprising.
But that's not how xDrips works. I've checked again and enabled "show Raw values in Graph" two steps down in the advanced settings and there they are...5.6 mg/dl...Ups.

**Comment by infossk** [comment]
Amazingly fast response. 🙂 Thank you for fix.

**Comment by infossk** [comment]
Bad news.  Even version 1.3.1 is not ok.  I rolled it back to 1.2.0 and will try to see where the problem is tomorrow.

**Comment by cmtjk** [comment]
Yeah, I marked 1.3.0+ as pre-releases. I also noticed something is fishy and I have already 1.3.2 running but have to lock at it tomorrow.
I've noticed that 1.3.1 xDrip broadcast never where successfull but xDrip wasn't logging something useful.

**Comment by infossk** [comment]
![IMG_20220907_010737](https://user-images.githubusercontent.com/8257881/188755612-57bf5c70-b1b0-4d9d-bab3-7a45a0e1faec.jpg)

**Comment by cmtjk** [comment]
@infossk can you try https://github.com/cmtjk/LinkUpConnect/releases/tag/v1.3.2 and check if it works now.

**Comment by infossk** [comment]
Thank you. But I will test it sometime in the evening.

**Comment by infossk** [comment]
I tested version 1.3.2.  Looks like it's fine now.
