### ISSUE TITLE
Crashes after update to xDrip 2024.04.19?

### ISSUE THREAD

**Issue by andrenicGH** [cmtjk/LinkUpConnect#16]
Using LibreLinkUp to get data and forward to xDrip+. It's been working well until I upgraded xDrip+ to version 2024.04.19. I believe previous version was 2023.11.14.
https://navid200.github.io/xDrip/docs/ReleaseNotes.html
Also recently updated phone to One UI 6.1 (Android 14). Samsung S23+

LibreLinkUp now seems to sop sending data a couple times each day. Needs to start LibreLinkUp again, and it works again immediately. Smells like a crash. No battery limitation or similar active on my phone.
Debug log doers not report anything useful, only connection to cloud service, which is OK.

Please let me know if I can provide any more info, or if similar issues are reported from others. 
Thank you very much for a fantastic app that plays a major part of my dia1 management :)

**Comment by cmtjk** [comment]
Hi @andrenicGH,

I've updated xDrip to 2024.04.19 myself and everything still works as expected. I have an Galaxy A53 wit OneUI 6.1, too.
Unfortunately LinkUpConnect doesn't create persistent crash logs and there are currently no plans to implement it.

To be honest it sounds like some kind of battery optimization but since you said it's not I'd like you to:
- reinstall LinkUpConnect
- check settings for battery optimization
- report back if the issue still occurs

**Comment by andrenicGH** [comment]
Thanks for quick feedback! 
I agree that sounds very likely yes, will reinstall, check and report.

**Comment by andrenicGH** [comment]
Hello again

Made a test as follows:

- Uninstalled LinkUpConnect
- Restarted phone
- Reinstalled LinkUpConnect (surprisingly the server address, credentials etc. were not reset to default, so I did not have to enter - anything to get it up and running after reinstall)
- Disabled battery optimization for the app
 
It still closed 1-3 times per day after this unfortunately.
I have always run the app without the permanent notification, since i use xDrip for that. I tested for a few days with notification enabled, and the app stayed alive then! Normally I have not granted the app permission to send notifications either, so I had to update that also of course. 

After further testing over a period of time, it seems the key is enabling the "permanent notification" in the app. I can disable notifications from the app in Android, so it does not display, but enabling the "permanent notification" checkbox is the key.
If I disable that, the app is killed or crashes a few times every day.
Not sure why this seems to be important (perhaps it helps keep the app alive), but anyway, I'm happy with the current state, thanks for your help and your effort making the app in the first place!

 

I also tried allowing and enabling the notification from the app (normally I don’t use this since xDrip+ has its own). This made no difference.
 

Is it worth trying to run the app for some time without forwarding to xDrip? To reveal whether this communication is what causes issues? Not sure whether the communication is one way only, and if changes in latest xDrip version can be to blame?

**Comment by cmtjk** [comment]
> After further testing over a period of time, it seems the key is enabling the "permanent notification" in the app.
Yes. It's necessary to run the app as foreground service by enabeling the 'Permanent notification'. Otherwise the app is killed by the system.

One might ask why there is an option for that and to be honest... I don't know why I added the checkbox.
Most likely to suppress the notification when only forwarding to xDrip is required (https://github.com/cmtjk/LinkUpConnect/commit/6fa724f3c4a3d42deb536958fe9d62d6b0400ff3) but I forgot that it's necessary.

Your solution seems the only viable to archieve that.

Thanks for the information and sorry for the inconvenience. Maybe I'll patch the app at some point.
