### ISSUE TITLE
only getting stale data [Now complete failure]

### ISSUE THREAD

**Issue by alanruttenberg** [cmtjk/LinkUpConnect#8]
Hi,
There was maintenance last night and when I was able to connect again, linkup connect will query the API, but only returns the last value before maintenance started. LibreLinkUp and the Libre3 app are both getting current data. Any ideas?

**Comment by alanruttenberg** [comment]
I just saw an announcement on https://status.freestyle.abbott/ that they are looking in to an outage. I'll close this for now and reopen once Abbot has their shit together if it is still a problem.

**Comment by alanruttenberg** [comment]
Now it just wont work at all. I get volley error, com.android.AuthFailureError. This for api-us.libreview.io and an account that is working with LinkUpConnect 
Somehow related to their update of LinkUpConnect to 4.7. Also as others have reported, the values in LinkUpConnect are delayed by 20 minutes.

**Comment by alanruttenberg** [comment]
Perhaps related : https://github.com/timoschlueter/nightscout-librelink-up/pull/101

**Comment by cmtjk** [comment]
Thanks for reporting, I'll habe a look at it later today and release a new version.

**Comment by alanruttenberg** [comment]
Thank you so so much!

**Comment by ruhrprinz** [comment]
Thanks for the great tool. I use it since last week. Can you please add a widget? It would be great to have a widget directly on the home screen with the same information as on the notification. If you would add the xDrip alert functionality and an open webserver like xDrip, I will be able to see the value on my smartwatch. xDrip is not usefull, because the xDrip value is far away from the actual.
Thank you very much...

**Comment by Trenpax** [comment]
Hey,

I still get the Volley error. I've reinstalled the app already. 
Is there still a bug maybe?

**Comment by cmtjk** [comment]
@ruhrprinz sorry, I'll have to keep it very simple since I have no time to add new features which require additional effort to maintain in the future. Everyone is free to fork it and add new features.

@Trenpax I don't know about any issues currently and it's working fine for me. I you still have errors please open a new issue.
